version: 1
jobs:
    build:
        docker:
            - image: circleci/node:10.5.2
        
        working_directory: ~/pgr/ui
        
        steps:
            - checkout
        
        -restore_cache:
            -keys:
                - v1-dependencies-{{ checksum "package.json" }}
                # fallback to using the latest cache if no exact match is found
                - v1-dependencies-
        
        -run:
            name: Install dependencies
            command: yarn install
        
        -save_cache:
            key: v1-dependencies-{{ checksum "package-lock.json" }}
            paths:
                - node_modules
        
        -run:
            name: UI unit tests
            command: yarn test
