# Generated by Django 2.2.6 on 2019-12-22 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20191207_1028'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criticreview',
            old_name='add_by',
            new_name='added_by',
        ),
        migrations.AddField(
            model_name='criticreview',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
    ]
