# Generated by Django 2.2.6 on 2019-12-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20191222_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticreview',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
