# Generated by Django 2.2.6 on 2019-11-10 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_show_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='discord_username',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mixer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='show_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitch',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='youtube',
        ),
    ]
