# Generated by Django 2.2.6 on 2019-11-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191110_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(null=True, upload_to='profile_images'),
        ),
    ]
