# Generated by Django 2.2.6 on 2019-11-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='parental_rating',
            field=models.CharField(choices=[('E', 'Everyone'), ('T', 'Teen'), ('M', 'Mature')], default=None, max_length=1, null=True),
        ),
    ]
