# Generated by Django 2.2.6 on 2019-11-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20191128_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='parental_rating',
            field=models.CharField(choices=[('E', 'Everyone'), ('T', 'Teen'), ('M', 'Mature')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
