# Generated by Django 2.2.6 on 2019-12-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='parental_rating',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
