# Generated by Django 2.2.6 on 2019-12-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20191202_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='parental_rating',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
