# Generated by Django 2.2.6 on 2019-12-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20191202_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='publisher',
            new_name='developer',
        ),
    ]
